### ISSUE TITLE
Any plan to upgrade it？

### ISSUE THREAD

**Issue by chengts95** [code-sam/graphblas_sparse_linear_algebra#26]
The new GraphBlas API is version 2.0.0  and suitesparse graphblas is 7.1.1.

**Comment by code-sam** [comment]
An update to using the latest version of SuiteSparse:GraphBLAS definately makes sense. But at the moment no such work is  planned yet.

**Comment by code-sam** [comment]
The latest release supports SuiteSparse:GraphBLAS v7.3.0. Changes to the API to implement GraphBLAS 2.0 are expected.

**Comment by code-sam** [comment]
The latest release already wraps around most of the APIs of SuiteSparse:GraphBLAS v7.3.0 and thereby supports most of GraphBLAS 2.0. There is no tracking issue. Are you missing a specific API?
In any case, the translation to Rust makes for a slightly different API in general. Progressive insight in how to implement the translation has made for most of the breaking changes so far, and may still continue to do so.
